# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestFinal():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testFinal(self):
    self.driver.get("https://www.apple.com/tw/shop/buy-iphone/iphone-12")
    self.driver.set_window_size(1106, 1040)
    self.driver.find_element(By.CSS_SELECTOR, "#Item16_1inch_label > .form-choiceselectorlabel-twocol").click()
    self.driver.find_element(By.ID, "dimensionColor-white").click()
    self.driver.find_element(By.CSS_SELECTOR, "#Item364gb_label .as-dimension-price").click()
    self.driver.execute_script("window.scrollTo(0,546)")
    self.driver.find_element(By.NAME, "add-to-cart").click()
    element = self.driver.find_element(By.NAME, "add-to-cart")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.NAME, "proceed").click()
    self.driver.find_element(By.ID, "shoppingCart.actions.navCheckout").click()
    self.driver.find_element(By.ID, "signIn.guestLogin.guestLogin").click()
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.ID, "password_text_field").send_keys("Isao0903")
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, "#rs-checkout-continue-button-bottom > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".as-storelocator-searchitem:nth-child(1) .form-selector-left-col").click()
    self.driver.execute_script("window.scrollTo(0,361)")
    self.driver.find_element(By.CSS_SELECTOR, ".rs-pickup-slot:nth-child(3) .form-selector-label > span").click()
    self.driver.find_element(By.ID, "2021-03-31timeWindows").click()
    dropdown = self.driver.find_element(By.ID, "2021-03-31timeWindows")
    dropdown.find_element(By.XPATH, "//option[. = '下午 2:15 – 下午 2:30']").click()
    self.driver.find_element(By.ID, "2021-03-31timeWindows").click()
    self.driver.find_element(By.ID, "rs-checkout-continue-button-bottom").click()
    self.driver.find_element(By.ID, "recon-0-177").click()
    self.driver.find_element(By.ID, "recon-0-177").send_keys("林")
    self.driver.find_element(By.ID, "recon-0-178").send_keys("肇勳")
    self.driver.find_element(By.ID, "recon-0-175").send_keys("404388")
    self.driver.find_element(By.ID, "recon-0-173").click()
    self.driver.find_element(By.ID, "recon-0-173").send_keys("remremtan0202@gmail.com")
    self.driver.find_element(By.ID, "recon-0-175").send_keys("0970404388")
    self.driver.find_element(By.ID, "rs-checkout-continue-button-bottom").click()
    self.driver.find_element(By.CSS_SELECTOR, "#checkout\\.billing\\.billingOptions\\.options\\.0-selector .row").click()
    self.driver.find_element(By.ID, "recon-0-297").click()
    self.driver.find_element(By.ID, "recon-0-297").send_keys("4705 3803 1455 4425")
    self.driver.find_element(By.ID, "recon-0-296").send_keys("10/25")
    self.driver.find_element(By.ID, "recon-0-295").click()
    self.driver.find_element(By.ID, "recon-0-295").send_keys("002")
    self.driver.find_element(By.ID, "recon-0-288").click()
    self.driver.find_element(By.ID, "recon-0-288").send_keys("林")
    self.driver.find_element(By.ID, "recon-0-289").send_keys("肇勳")
    self.driver.find_element(By.ID, "recon-0-308-city").click()
    dropdown = self.driver.find_element(By.ID, "recon-0-308-city")
    dropdown.find_element(By.XPATH, "//option[. = '新北市']").click()
    self.driver.find_element(By.ID, "recon-0-308-city").click()
    self.driver.find_element(By.ID, "recon-0-291").click()
    self.driver.find_element(By.ID, "recon-0-291").send_keys("板橋區實踐路93巷57號4樓")
    self.driver.find_element(By.ID, "recon-0-286").click()
    self.driver.find_element(By.ID, "recon-0-286").send_keys("220")
    self.driver.find_element(By.CSS_SELECTOR, ".form-selector-group:nth-child(5) .row .row").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-selector-group:nth-child(4) .form-selector-title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-selector-group:nth-child(1) .column .row").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-selector-group:nth-child(2) .form-selector-label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-selector-group:nth-child(3) > .rs-fapiao-option .form-selector-label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-selector-group:nth-child(4) .form-selector-label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-selector-group:nth-child(5) .form-selector-label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-selector-group:nth-child(5) .row .row").click()
    self.driver.find_element(By.ID, "recon-0-229").click()
    self.driver.find_element(By.ID, "recon-0-229").send_keys("1221")
    self.driver.find_element(By.ID, "recon-0-230").click()
    self.driver.find_element(By.ID, "recon-0-230").send_keys("1221")
    self.driver.find_element(By.CSS_SELECTOR, ".rs-fapiao").click()
    self.driver.find_element(By.CSS_SELECTOR, "#rs-checkout-continue-button-bottom > span").click()
    self.driver.find_element(By.ID, "rs-checkout-continue-button-bottom").click()
  
